package activation;

import java.awt.Desktop;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import oshi.SystemInfo;

/**
 *
 * @author Mustafa Mohamed
 */
public class ActivationDialog extends javax.swing.JDialog {

    /**
     * Creates new form ActivationDialog
     *
     * @param parent
     * @param modal
     */
    public ActivationDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jLabelHeader1.putClientProperty("FlatLaf.styleClass", "h3");
        jLabelHeader2.putClientProperty("FlatLaf.styleClass", "h3");
        jTextFieldCode.putClientProperty("FlatLaf.styleClass", "h3");
        jTextFieldCode.setText(getSerialNumber());
    }

    private String getSerialNumber() {
        var hal = new SystemInfo().getHardware();
        var serialNumber = hal.getComputerSystem().getSerialNumber();
        return serialNumber;
    }

    private void onBrowse() {
        JFileChooser chooser = new JFileChooser();
        chooser.setDialogTitle("Select Activation File");
        chooser.setMultiSelectionEnabled(false);
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int result = chooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            try {
                boolean isActivated = Activate.checkActivation(chooser.getSelectedFile().getAbsolutePath());
                if (isActivated) {
                    JOptionPane.showMessageDialog(this, """
                                                        Congragulations! Activation Succeeded.
                                                        All Keen Clinic features are now enabled.""",
                            "Activation Succeeded", JOptionPane.INFORMATION_MESSAGE);
                    close();
                } else {
                    JOptionPane.showMessageDialog(this, """
                                                        Oops! That didn't work.
                                                        Please contact support for assistance.""",
                            "Activaion Failed", JOptionPane.WARNING_MESSAGE);
                }
            } catch (Exception ex) {
                Logger.getLogger(ActivationDialog.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, """
                                                    An error occurred while checking the activation code.
                                                    Please ensure you are connected to the internet.""",
                        "Activation Failed", JOptionPane.WARNING_MESSAGE);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelHeader1 = new javax.swing.JLabel();
        jLabelHeader2 = new javax.swing.JLabel();
        jButtonBrowseFile = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jXHyperlinkGetInTouch = new org.jdesktop.swingx.JXHyperlink();
        jButtonClose = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCode = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Activate Keen Clinic");

        jLabelHeader1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHeader1.setText("You are using an evaluation version of this program.");

        jLabelHeader2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelHeader2.setText("To unlock all features, please activate Keen Clinic.");

        jButtonBrowseFile.setText("Select File...");
        jButtonBrowseFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBrowseFileActionPerformed(evt);
            }
        });

        jLabel6.setText("Don't have an activation code?");

        jXHyperlinkGetInTouch.setText("Get in touch");
        jXHyperlinkGetInTouch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXHyperlinkGetInTouchActionPerformed(evt);
            }
        });

        jButtonClose.setText("Close");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Share this code with GVL Digital Solutions to get an activation code");

        jLabel2.setText("Already have an activation code?");

        jTextFieldCode.setEditable(false);
        jTextFieldCode.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCode.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelHeader1, javax.swing.GroupLayout.DEFAULT_SIZE, 533, Short.MAX_VALUE)
                    .addComponent(jLabelHeader2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonClose, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButtonBrowseFile))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jXHyperlinkGetInTouch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(148, 148, 148))))
                    .addComponent(jTextFieldCode))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelHeader1)
                .addGap(18, 18, 18)
                .addComponent(jLabelHeader2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBrowseFile)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jXHyperlinkGetInTouch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(jButtonClose)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        onClose();
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void jXHyperlinkGetInTouchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXHyperlinkGetInTouchActionPerformed
        onGetInTouch();
    }//GEN-LAST:event_jXHyperlinkGetInTouchActionPerformed

    private void jButtonBrowseFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBrowseFileActionPerformed
        onBrowse();
    }//GEN-LAST:event_jButtonBrowseFileActionPerformed

    private void onGetInTouch() {
        try {
            Desktop.getDesktop().browse(new URI("https://gvlsolutions.com/contact/"));
        } catch (URISyntaxException | IOException ex) {
            Logger.getLogger(ActivationDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void onClose() {
        close();
    }

    private void close() {
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBrowseFile;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelHeader1;
    private javax.swing.JLabel jLabelHeader2;
    private javax.swing.JTextField jTextFieldCode;
    private org.jdesktop.swingx.JXHyperlink jXHyperlinkGetInTouch;
    // End of variables declaration//GEN-END:variables
}
