package main.patient.visit;

import main.patient.visit.prescription.PrescriptionTableModel;
import main.patient.visit.prescription.Prescription;
import database.AppProperties;
import java.awt.event.WindowEvent;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import static main.drug.event.GlobalDrugEventManager.DRUG_EVENT_MANAGER;
import main.patient.patient.NewPatient;
import main.patient.patient.Patient;
import main.patient.visit.prescription.AllowNegativeShelfEvent;
import main.patient.visit.prescription.EditPrescription;
import static main.patient.visit.prescription.GlobalPrescriptionEventManager.PRESCRIPTION_EVENT_MANAGER;
import main.patient.visit.prescription.NewPrescription;
import main.patient.visit.prescription.PrescriptionAddedEvent;
import main.patient.visit.prescription.PrescriptionDeletedEvent;
import main.patient.visit.prescription.PrescriptionEventListener;
import main.patient.visit.prescription.PrescriptionTempAddedEvent;
import main.patient.visit.prescription.PrescriptionTempDeletedEvent;
import main.patient.visit.prescription.PrescriptionTempUpdatedEvent;
import main.patient.visit.prescription.PrescriptionUpdatedEvent;
import utils.Utils;

/**
 *
 * @author Mustafa Mohamed
 */
public class NewOutpatient extends javax.swing.JDialog implements PrescriptionEventListener {

    private final java.awt.Frame parent;

    private int patientId;
    private final PrescriptionTableModel tableModel = new PrescriptionTableModel();
    /**
     * This is not the visit id. It is just a random number to identify this
     * dialog.
     */
    private final int newOutpatientId;

    private final DrugsOutOfShelf dialogOutOfShelf;

    /**
     * Creates new form NewOutpatient
     *
     * @param parent
     * @param modal
     */
    public NewOutpatient(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.parent = parent;
        this.newOutpatientId = Utils.getUniqueId();
        initComponents();
        jLabelStatus.setText("");
        ChangeListener l = (ChangeEvent e) -> {
            setBMI();
        };
        jSpinnerHeight.getModel().addChangeListener(l);
        jSpinnerWeight.getModel().addChangeListener(l);
        setupPrescriptionTable();
        dialogOutOfShelf = new DrugsOutOfShelf(this, false);
        dialogOutOfShelf.setNewOutpatientId(newOutpatientId);
    }

    public void initWindow() {
        int x = getLocation().x;
        int y = getLocation().y;
        x = Integer.parseInt(AppProperties.get("NewOutpatientX", String.valueOf(x)));
        y = Integer.parseInt(AppProperties.get("NewOutpatientY", String.valueOf(y)));
        setLocation(x, y);

    }

    private void setupPrescriptionTable() {
        jTablePrescriptions.setModel(tableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenuPrescriptions = new javax.swing.JPopupMenu();
        jMenuItemAdd = new javax.swing.JMenuItem();
        jMenuItemEdit = new javax.swing.JMenuItem();
        jMenuItemDelete = new javax.swing.JMenuItem();
        jButtonCancel = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();
        jTabbedPane = new javax.swing.JTabbedPane();
        jPanelPhysicals = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSpinnerWeight = new javax.swing.JSpinner();
        jSpinnerHeight = new javax.swing.JSpinner();
        jTextFieldVisual = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaComplaints = new javax.swing.JTextArea();
        jLabelBMI = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jXHyperlinkSelectPatient = new org.jdesktop.swingx.JXHyperlink();
        jXHyperlinkAddPatient = new org.jdesktop.swingx.JXHyperlink();
        jLabelPatientName = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldOPD = new javax.swing.JTextField();
        jPanelExams = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaPhysicalExam = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaLabExam = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jPanelOutcome = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaDiagnosis = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextAreaTreatment = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextAreaRemarks = new javax.swing.JTextArea();
        jComboBoxOutcome = new javax.swing.JComboBox<>();
        jLabelStatus = new javax.swing.JLabel();
        jPanelPrescription = new javax.swing.JPanel();
        jButtonAddPrescription = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTablePrescriptions = new javax.swing.JTable();
        jButtonNext = new javax.swing.JButton();
        jButtonPrevious = new javax.swing.JButton();

        jPopupMenuPrescriptions.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jPopupMenuPrescriptionsPopupMenuWillBecomeVisible(evt);
            }
        });

        jMenuItemAdd.setText("Add...");
        jPopupMenuPrescriptions.add(jMenuItemAdd);

        jMenuItemEdit.setText("Edit...");
        jMenuItemEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEditActionPerformed(evt);
            }
        });
        jPopupMenuPrescriptions.add(jMenuItemEdit);

        jMenuItemDelete.setText("Delete");
        jMenuItemDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDeleteActionPerformed(evt);
            }
        });
        jPopupMenuPrescriptions.add(jMenuItemDelete);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Outpatient Visit");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jLabel1.setText("Weight (kg)");

        jLabel2.setText("Height(m)");

        jLabel3.setText("BMI");

        jLabel4.setText("Visual acuity");

        jLabel5.setText("Complaints");

        jSpinnerWeight.setModel(new javax.swing.SpinnerNumberModel(0.0f, 0.0f, null, 1.0f));

        jSpinnerHeight.setModel(new javax.swing.SpinnerNumberModel(0.0f, 0.0f, null, 1.0f));

        jTextAreaComplaints.setColumns(20);
        jTextAreaComplaints.setRows(5);
        jScrollPane1.setViewportView(jTextAreaComplaints);

        jLabelBMI.setText("Enter weight and height to show patient BMI");

        jLabel12.setText("Patient");

        jXHyperlinkSelectPatient.setText("Select patient...");
        jXHyperlinkSelectPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXHyperlinkSelectPatientActionPerformed(evt);
            }
        });

        jXHyperlinkAddPatient.setText("Add patient...");
        jXHyperlinkAddPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXHyperlinkAddPatientActionPerformed(evt);
            }
        });

        jLabelPatientName.setText("No patient selected");

        jLabel13.setText("OPD #");

        javax.swing.GroupLayout jPanelPhysicalsLayout = new javax.swing.GroupLayout(jPanelPhysicals);
        jPanelPhysicals.setLayout(jPanelPhysicalsLayout);
        jPanelPhysicalsLayout.setHorizontalGroup(
            jPanelPhysicalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPhysicalsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPhysicalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPhysicalsLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanelPhysicalsLayout.createSequentialGroup()
                        .addGroup(jPanelPhysicalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanelPhysicalsLayout.createSequentialGroup()
                                .addGroup(jPanelPhysicalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelPhysicalsLayout.createSequentialGroup()
                                        .addGroup(jPanelPhysicalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel13))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanelPhysicalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextFieldOPD, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jSpinnerWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jSpinnerHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelBMI)
                                            .addComponent(jTextFieldVisual, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                                            .addComponent(jLabelPatientName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jXHyperlinkSelectPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel12))
                                .addGap(18, 18, 18)
                                .addComponent(jXHyperlinkAddPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(49, 163, Short.MAX_VALUE))))
        );
        jPanelPhysicalsLayout.setVerticalGroup(
            jPanelPhysicalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPhysicalsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPhysicalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jXHyperlinkSelectPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXHyperlinkAddPatient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPatientName))
                .addGap(18, 18, 18)
                .addGroup(jPanelPhysicalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldOPD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelPhysicalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jSpinnerWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelPhysicalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jSpinnerHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelPhysicalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabelBMI, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPhysicalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldVisual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane.addTab("Physicals", jPanelPhysicals);

        jLabel6.setText("Physical exam");

        jTextAreaPhysicalExam.setColumns(20);
        jTextAreaPhysicalExam.setRows(5);
        jScrollPane2.setViewportView(jTextAreaPhysicalExam);

        jTextAreaLabExam.setColumns(20);
        jTextAreaLabExam.setRows(5);
        jScrollPane3.setViewportView(jTextAreaLabExam);

        jLabel7.setText("Lab exam");

        javax.swing.GroupLayout jPanelExamsLayout = new javax.swing.GroupLayout(jPanelExams);
        jPanelExams.setLayout(jPanelExamsLayout);
        jPanelExamsLayout.setHorizontalGroup(
            jPanelExamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelExamsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelExamsLayout.createSequentialGroup()
                .addGroup(jPanelExamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
                    .addGroup(jPanelExamsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        jPanelExamsLayout.setVerticalGroup(
            jPanelExamsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelExamsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane.addTab("Exams", jPanelExams);

        jLabel8.setText("Outcome");

        jLabel9.setText("Diagnosis");

        jTextAreaDiagnosis.setColumns(20);
        jTextAreaDiagnosis.setRows(5);
        jScrollPane4.setViewportView(jTextAreaDiagnosis);

        jLabel10.setText("Treatment");

        jTextAreaTreatment.setColumns(20);
        jTextAreaTreatment.setRows(5);
        jScrollPane5.setViewportView(jTextAreaTreatment);

        jLabel11.setText("Remarks");

        jTextAreaRemarks.setColumns(20);
        jTextAreaRemarks.setRows(5);
        jScrollPane6.setViewportView(jTextAreaRemarks);

        jComboBoxOutcome.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alive", "Dead" }));

        jLabelStatus.setText("jLabel1");

        javax.swing.GroupLayout jPanelOutcomeLayout = new javax.swing.GroupLayout(jPanelOutcome);
        jPanelOutcome.setLayout(jPanelOutcomeLayout);
        jPanelOutcomeLayout.setHorizontalGroup(
            jPanelOutcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOutcomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOutcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
                    .addComponent(jScrollPane5)
                    .addComponent(jScrollPane6)
                    .addComponent(jLabelStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelOutcomeLayout.createSequentialGroup()
                        .addGroup(jPanelOutcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addGroup(jPanelOutcomeLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxOutcome, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 472, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelOutcomeLayout.setVerticalGroup(
            jPanelOutcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelOutcomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelOutcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBoxOutcome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(jLabelStatus)
                .addContainerGap())
        );

        jTabbedPane.addTab("Diagnosis and Treatment", jPanelOutcome);

        jButtonAddPrescription.setText("Add...");
        jButtonAddPrescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddPrescriptionActionPerformed(evt);
            }
        });

        jTablePrescriptions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "#", "Drug", "Quantity", "Dosage", "Remarks"
            }
        ));
        jTablePrescriptions.setComponentPopupMenu(jPopupMenuPrescriptions);
        jTablePrescriptions.setRowHeight(33);
        jTablePrescriptions.setShowHorizontalLines(true);
        jTablePrescriptions.setShowVerticalLines(true);
        jTablePrescriptions.setSurrendersFocusOnKeystroke(true);
        jScrollPane7.setViewportView(jTablePrescriptions);
        jTablePrescriptions.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        javax.swing.GroupLayout jPanelPrescriptionLayout = new javax.swing.GroupLayout(jPanelPrescription);
        jPanelPrescription.setLayout(jPanelPrescriptionLayout);
        jPanelPrescriptionLayout.setHorizontalGroup(
            jPanelPrescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrescriptionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPrescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPrescriptionLayout.createSequentialGroup()
                        .addComponent(jButtonAddPrescription)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelPrescriptionLayout.setVerticalGroup(
            jPanelPrescriptionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrescriptionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonAddPrescription)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 447, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane.addTab("Prescriptions", jPanelPrescription);

        jButtonNext.setText("Next");
        jButtonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextActionPerformed(evt);
            }
        });

        jButtonPrevious.setText("Previous");
        jButtonPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPreviousActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonPrevious)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonNext)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancel)
                    .addComponent(jButtonSave)
                    .addComponent(jButtonNext)
                    .addComponent(jButtonPrevious))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        close();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jXHyperlinkAddPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXHyperlinkAddPatientActionPerformed
        onAddPatient();
    }//GEN-LAST:event_jXHyperlinkAddPatientActionPerformed

    private void jXHyperlinkSelectPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXHyperlinkSelectPatientActionPerformed
        onSelectPatient();
    }//GEN-LAST:event_jXHyperlinkSelectPatientActionPerformed

    private void jButtonPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPreviousActionPerformed
        int tab = jTabbedPane.getSelectedIndex();
        if (tab > 0) {
            jTabbedPane.setSelectedIndex(tab - 1);
        }
    }//GEN-LAST:event_jButtonPreviousActionPerformed

    private void jButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextActionPerformed
        int tab = jTabbedPane.getSelectedIndex();
        if (tab < jTabbedPane.getTabCount() - 1) {
            jTabbedPane.setSelectedIndex(tab + 1);
        }
    }//GEN-LAST:event_jButtonNextActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        onSave();
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        saveWindowConfig();
    }//GEN-LAST:event_formWindowClosing

    private void jButtonAddPrescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddPrescriptionActionPerformed
        onAddPrescription();
    }//GEN-LAST:event_jButtonAddPrescriptionActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        PRESCRIPTION_EVENT_MANAGER.addListener(this);
        PRESCRIPTION_EVENT_MANAGER.addListener(dialogOutOfShelf);

        DRUG_EVENT_MANAGER.addListener(dialogOutOfShelf);

    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        PRESCRIPTION_EVENT_MANAGER.removeListener(this);
        PRESCRIPTION_EVENT_MANAGER.removeListener(dialogOutOfShelf);

        DRUG_EVENT_MANAGER.removeListener(dialogOutOfShelf);
    }//GEN-LAST:event_formWindowClosed

    private void jMenuItemEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEditActionPerformed
        onEditPrescription();
    }//GEN-LAST:event_jMenuItemEditActionPerformed

    private void jPopupMenuPrescriptionsPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jPopupMenuPrescriptionsPopupMenuWillBecomeVisible
        onPopupPrescriptionsVisible();
    }//GEN-LAST:event_jPopupMenuPrescriptionsPopupMenuWillBecomeVisible

    private void jMenuItemDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDeleteActionPerformed
        onDeletePrescriptions();
    }//GEN-LAST:event_jMenuItemDeleteActionPerformed

    private void onPopupPrescriptionsVisible() {
        int selected = jTablePrescriptions.getSelectedRowCount();
        jMenuItemEdit.setEnabled(selected == 1);
        jMenuItemDelete.setEnabled(selected > 0);
    }

    private void onAddPrescription() {
        NewPrescription dialog = new NewPrescription(this, false, 0, false);
        dialog.setLocationRelativeTo(this);
        Utils.closeDialogOnEscape(dialog);
        dialog.setNewOutpatientId(newOutpatientId);
        dialog.setVisible(true);
    }

    private void onEditPrescription() {
        int selected = jTablePrescriptions.getSelectedRowCount();
        if (selected == 1) {
            Prescription p = tableModel.getRowItem(
                    jTablePrescriptions.convertRowIndexToModel(jTablePrescriptions.getSelectedRow()));
            EditPrescription dialog = new EditPrescription(this, false, p, false);
            dialog.setLocationRelativeTo(this);
            Utils.closeDialogOnEscape(dialog);
            dialog.setNewOutpatientId(newOutpatientId);
            dialog.setVisible(true);
        }
    }

    private void onDeletePrescriptions() {
        if (jTablePrescriptions.getSelectedRowCount() > 0) {
            List<Prescription> prescriptions = new ArrayList<>();
            for (int i : jTablePrescriptions.getSelectedRows()) {
                prescriptions.add(tableModel.getRowItem(jTablePrescriptions.convertRowIndexToModel(i)));
            }
            // the two loops are needed so that we don't modify the model while processing it
            for (Prescription p : prescriptions) {
                PRESCRIPTION_EVENT_MANAGER.notifyPrescriptionTempDeleted(
                        new PrescriptionTempDeletedEvent(newOutpatientId, p));
            }
        }
    }

    private void onAddPatient() {
        NewPatient dialog = new NewPatient(parent, true);
        dialog.setLocationRelativeTo(this);
        Utils.closeDialogOnEscape(dialog);
        dialog.setVisible(true);
        if (dialog.getPatientId() > 0) {
            this.patientId = dialog.getPatientId();
            try {
                Patient patient = Patient.getPatient(this.patientId);
                jLabelPatientName.setText(patient.formatPatientName());
            } catch (SQLException ex) {
                Logger.getLogger(NewOutpatient.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "An error occurred. Please try again after a few moments.", "Error", JOptionPane.WARNING_MESSAGE);
                this.patientId = 0;
                jLabelPatientName.setText("No patient selected");
            }
        }
    }

    @Override
    public void onAllowNegativeShelf(AllowNegativeShelfEvent event) {
        if (event.eventId == newOutpatientId) {
            allowNegativeShelf = true;
            this.requestFocus();
            onSave();
        }
    }

    private boolean allowNegativeShelf = false;

    private void onSave() {
        if (patientId <= 0) {
            JOptionPane.showMessageDialog(this,
                    "Please add a patient for the visit or select an existing patient.",
                    "No Patient Seleted", JOptionPane.WARNING_MESSAGE);
            jTabbedPane.setSelectedIndex(0);
        } else if (!dialogOutOfShelf.isCanSafelyPrescribe() && !allowNegativeShelf) {
            if (!dialogOutOfShelf.isVisible()) {
                dialogOutOfShelf.setLocationRelativeTo(this);
                dialogOutOfShelf.setVisible(true);
            }
            dialogOutOfShelf.requestFocus();

        } else {
            Outpatient visit = new Outpatient();
            visit.complaints = jTextAreaComplaints.getText().trim();
            visit.diagnosis = jTextAreaDiagnosis.getText().trim();
            visit.height = (float) jSpinnerHeight.getValue();
            visit.labExam = jTextAreaLabExam.getText().trim();
            visit.opdNumber = jTextFieldOPD.getText().trim();
            visit.outcome = jComboBoxOutcome.getSelectedIndex() < 0 ? null : (String) jComboBoxOutcome.getSelectedItem();
            visit.patientId = patientId;
            visit.physicalExam = jTextAreaPhysicalExam.getText().trim();
            visit.remarks = jTextAreaRemarks.getText().trim();
            visit.treatment = jTextAreaTreatment.getText().trim();
            visit.visitDate = LocalDateTime.now();
            visit.visualAcuity = jTextFieldVisual.getText().trim();
            visit.weight = (float) jSpinnerWeight.getValue();
            for (Prescription p: tableModel.getRowItems()){
                visit.addPrescription(p);
            }
            boolean saved = false;
            try {
                Outpatient.saveOutpatient(visit);
                saved = true;
            } catch (SQLException ex) {
                Logger.getLogger(NewOutpatient.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, """
                                                    Something went wrong while saving the visit.
                                                    Please try again later.""", "Failed", JOptionPane.WARNING_MESSAGE);
            } finally {
                if (saved) {
                    JOptionPane.showMessageDialog(this, "Visit saved successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
                    close();
                }
            }
        }
    }

    private void onSelectPatient() {
        NewVisitSelectPatient dialog = new NewVisitSelectPatient(parent, true);
        dialog.setLocationRelativeTo(this);
        Utils.closeDialogOnEscape(dialog);
        dialog.setVisible(true);
        if (dialog.getPatientId() > 0) {
            this.patientId = dialog.getPatientId();
            try {
                Patient patient = Patient.getPatient(this.patientId);
                jLabelPatientName.setText(patient.formatPatientName());
            } catch (SQLException ex) {
                Logger.getLogger(NewOutpatient.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "An error occurred. Please try again after a few moments.", "Error", JOptionPane.WARNING_MESSAGE);
                this.patientId = 0;
                jLabelPatientName.setText("No patient selected");
            }
        }
    }

    private void close() {
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }

    private void setBMI() {
        float weight = (float) jSpinnerWeight.getValue();
        float height = (float) jSpinnerHeight.getValue();
        if (weight > 0 && height > 0) {
            jLabelBMI.setText(String.valueOf(weight / (height * height)));
        } else {
            jLabelBMI.setText("Enter weight and height above to calculate BMI");
        }
    }

    private void saveWindowConfig() {
        // we won't save the width and height because the user might resize the window to hide some controls
        // a better approach would probably be to limit the minimum size!
        //int width = getWidth();
        //int height = getHeight();
        int x = getLocation().x;
        int y = getLocation().y;
        //AppProperties.put("NewOutpatientWidth", String.valueOf(width));
        //AppProperties.put("NewOutpatientHeight", String.valueOf(height));
        AppProperties.put("NewOutpatientX", String.valueOf(x));
        AppProperties.put("NewOutpatientY", String.valueOf(y));
    }

    @Override
    public void onPrescriptionAdded(PrescriptionAddedEvent event) {

    }

    @Override
    public void onPrescriptionUpdated(PrescriptionUpdatedEvent event) {

    }

    @Override
    public void onPrescriptionDeleted(PrescriptionDeletedEvent event) {

    }

    @Override
    public void onPrescriptionTempAdded(PrescriptionTempAddedEvent event) {
        Prescription prescription = event.prescription;
        if (event.eventId == newOutpatientId) {
            tableModel.addRowItem(prescription);
        }
    }

    @Override
    public void onPrescriptionTempUpdated(PrescriptionTempUpdatedEvent event) {
        if (event.eventId == newOutpatientId) {
            Prescription p = event.prescription;
            for (int i = 0; i < tableModel.size(); i++) {
                Prescription c = tableModel.getRowItem(i);
                if (c.getTempId() == p.getTempId()) {
                    c.dosage = p.dosage;
                    c.drugId = p.drugId;
                    c.drugName = p.drugName;
                    c.quantity = p.quantity;
                    c.remarks = p.remarks;
                    c.visitId = p.visitId;
                    break;
                }
            }
        }
    }

    @Override
    public void onPrescriptionTempDeleted(PrescriptionTempDeletedEvent event) {
        if (event.eventId == newOutpatientId) {
            Prescription prescription = event.prescription;
            Prescription toDelete = null;
            for (int i = 0; i < tableModel.size(); i++) {
                Prescription c = tableModel.getRowItem(i);
                if (c.getTempId() == prescription.getTempId()) {
                    toDelete = c;
                    break;
                }
            }
            if (toDelete != null) {
                tableModel.removeRowItem(toDelete);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddPrescription;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonNext;
    private javax.swing.JButton jButtonPrevious;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JComboBox<String> jComboBoxOutcome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelBMI;
    private javax.swing.JLabel jLabelPatientName;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JMenuItem jMenuItemAdd;
    private javax.swing.JMenuItem jMenuItemDelete;
    private javax.swing.JMenuItem jMenuItemEdit;
    private javax.swing.JPanel jPanelExams;
    private javax.swing.JPanel jPanelOutcome;
    private javax.swing.JPanel jPanelPhysicals;
    private javax.swing.JPanel jPanelPrescription;
    private javax.swing.JPopupMenu jPopupMenuPrescriptions;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSpinner jSpinnerHeight;
    private javax.swing.JSpinner jSpinnerWeight;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTable jTablePrescriptions;
    private javax.swing.JTextArea jTextAreaComplaints;
    private javax.swing.JTextArea jTextAreaDiagnosis;
    private javax.swing.JTextArea jTextAreaLabExam;
    private javax.swing.JTextArea jTextAreaPhysicalExam;
    private javax.swing.JTextArea jTextAreaRemarks;
    private javax.swing.JTextArea jTextAreaTreatment;
    private javax.swing.JTextField jTextFieldOPD;
    private javax.swing.JTextField jTextFieldVisual;
    private org.jdesktop.swingx.JXHyperlink jXHyperlinkAddPatient;
    private org.jdesktop.swingx.JXHyperlink jXHyperlinkSelectPatient;
    // End of variables declaration//GEN-END:variables

}
